name: dev
variables:
  - name: EMAIL
    value: therapist@example.com
  - name: PASSWORD
    value: test123456
  - secret: true
    name: ACCESS_TOKEN
  - name: BASE_URL
    value: http://localhost:3000
