name: dev
variables:
  - name: ADMIN_EMAIL
    value: admin@example.com
  - name: THERAPIST_EMAIL
    value: therapist@example.com
  - name: GUARDIAN_EMAIL
    value: guardian@example.com
  - name: CHILD_EMAIL
    value: child@example.com
  - name: DEFAULT_PASSWORD
    value: test123456
  - name: ADMIN_PASSWORD
    value: test123456
  - name: THERAPIST_PROFILE_ID
    value: cmlh1g3h20004o6q40myx1tgp
  - name: GUARDIAN_PROFILE_ID
    value: cmlh1g3he0005o6q4v3474845
  - name: CHILD_PROFILE_ID
    value: cmlh1g3hm0006o6q48fxs03i7
  - name: ACCESS_TOKEN_ADMIN
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWxoMWczZm4wMDAwbzZxNGtwa3Q3anQyIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc3MDc1NTcxMSwiZXhwIjoxNzcxMzYwNTExfQ.ECKZ7Y6jDMdzZPD5jA95Qd70FLW_dgAyL0mKvLCndfQ
  - name: ACCESS_TOKEN_THERAPIST
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbWxoMWczZ28wMDAybzZxNHpwc3gxOTR5IiwiZW1haWwiOiJ0aGVyYXBpc3RAZXhhbXBsZS5jb20iLCJyb2xlIjoiVEhFUkFQSVNUIiwiaWF0IjoxNzcwNzU1ODA4LCJleHAiOjE3NzEzNjA2MDh9.gI6IS3HRNtXBso1P9fuIoVdg2Nq54KYOrgHXmC6X_oU
  - name: ACCESS_TOKEN_GUARDIAN
    value: ""
  - name: ACCESS_TOKEN_CHILD
    value: ""
  - name: BASE_URL
    value: http://localhost:3000
